FROM debian

WORKDIR /home/work

RUN apt-get update
RUN apt-get install -y \
bison \
texinfo \
gawk \
binutils \
g++ \
xz-utils \
patch \
make \
m4 \
bzip2 \
vim \
ssh \
gdb \
zsh

RUN ln -sf /bin/sh /bin/bash

