#!/bin/bash

function _echo_info() {
   echo -e "\e[32m ${@} \e[0m"
}

function _echo_err() {
   echo -e "\e[31m ${@} \e[0m"
}

function _exec() {
    CMD=${@}
    __run_cmd ${CMD}
}

function __configure() {
    CMD="../configure ${@}"
    __run_cmd ${CMD}
}

function _configure() {
    CMD="./configure ${@}"
    __run_cmd ${CMD}
}

function _make () {
    CMD="make -j${MAKE_JOBS_NUM} ${@}"
    __run_cmd ${CMD}
}

function _make_check() {
    CMD="make -j ${MAKE_JOBS_NUM} check ${@}"
    __run_cmd ${CMD}
}

function __run_cmd() {
    ¦   LOG=${SCRIPT_DIR}/logs/${CUR_PACK}.tmp.log
    LOG_ERR=${SCRIPT_DIR}/logs/${CUR_PACK}.tmp.err

    echo ${@}
    ${@} >>${LOG} 2>>${LOG_ERR} || _echo_err "Failed"
}

export -f _echo_err     \
        _echo_info      \
        _exec           \
        _configure      \
        __configure     \
        _make           \
        _make_check
